version: '2'
networks:
  test:
    name: test_network

services:
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=Admin
      - COUCHDB_PASSWORD=Adminpw
    ports:
      - "5984:5984"
    networks:
      - test
  
  peer0.org1.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=Admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=Adminpw
    depends_on:
      - couchdb0

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=Admin
      - COUCHDB_PASSWORD=Adminpw
    ports:
      - "7984:5984"
    networks:
      - test
  
  peer0.org2.example.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=Admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=Adminpw
    depends_on:
      - couchdb1
